version: "3.8"

services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
      - ./backend/.env:/usr/src/app/.env
      - backend_prisma_client:/usr/src/app/generated
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
  backend_node_modules:
  backend_prisma_client:
  frontend_node_modules:
