version: "3.8"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./.env:/usr/src/app/.env
      - ./__tests__:/usr/src/app/__tests__
      - node_modules:/usr/src/app/node_modules
      - prisma_client:/usr/src/app/generated

    command: sh -c "npx prisma migrate dev && npm run dev"
    
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db_data:
  node_modules:
  prisma_client:
